galaxy_info:
  author: Nikolai Malinin
  description: Nginx playbook

  license: MIT

  min_ansible_version: 2.0

  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags:
    - networking

dependencies: []
