# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :bash => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end

          box.vm.provision "file", source: "script.sh", destination: "~/script.sh"
          box.vm.provision "file", source: "cron_report", destination: "~/cron_report"
          box.vm.provision "file", source: "access-4560-644067.log", destination: "~/access-4560-644067.log"

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install mailx -y
            chmod +x ~vagrant/script.sh
            crontab ~vagrant/cron_report
          SHELL
      end
  end
end
